#!/usr/bin/env bash
# ==============================================================================
# YetiForge Installer — Service Setup (systemd + nginx)
# ==============================================================================

setup_services() {
    step_header "Setting Up Services"

    local service_user="${INSTALL_USER}"
    local service_dir="${INSTALL_DIR}"
    local node_path
    node_path=$(which node)

    # ──────────────────────────────────────────────
    # systemd Service
    # ──────────────────────────────────────────────
    log_step "Generating systemd service..."

    cat > /tmp/yetiforge.service << SVCFILE
[Unit]
Description=YetiForge AI Bot Framework
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=${service_user}
WorkingDirectory=${service_dir}
ExecStart=${node_path} dist/index.js
Restart=always
RestartSec=10
EnvironmentFile=${service_dir}/.env

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=${service_dir}/data ${service_dir}
ProtectHome=false

# Resource limits
LimitNOFILE=65536
MemoryMax=1G

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=tiffbot

[Install]
WantedBy=multi-user.target
SVCFILE

    $SUDO_CMD cp /tmp/yetiforge.service /etc/systemd/system/tiffbot.service
    $SUDO_CMD systemctl daemon-reload
    $SUDO_CMD systemctl enable tiffbot >> "$INSTALL_LOG" 2>&1

    log_success "systemd service installed and enabled"

    # ──────────────────────────────────────────────
    # Nginx Configuration
    # ──────────────────────────────────────────────

    if [[ "$HAS_DOMAIN" == "true" ]] || [[ -n "$CFG_DOMAIN" ]]; then
        log_step "Generating Nginx configuration..."

        local server_name="${CFG_DOMAIN}"
        local status_port="${CFG_PORT:-3069}"
        local client_dist="${service_dir}/status/client/dist"

        cat > /tmp/yetiforge-nginx.conf << NGINXCONF
# YetiForge — Nginx Reverse Proxy
# Generated by installer on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

upstream yetiforge_api {
    server 127.0.0.1:${status_port};
    keepalive 32;
}

server {
    listen 80;
    listen [::]:80;
    server_name ${server_name};

    # Redirect to HTTPS if SSL is configured later
    # Uncomment the next two lines after running SSL setup:
    # return 301 https://\$host\$request_uri;
    # }
    # server {
    # listen 443 ssl http2;
    # listen [::]:443 ssl http2;
    # server_name ${server_name};
    # ssl_certificate /etc/letsencrypt/live/${server_name}/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/${server_name}/privkey.pem;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript image/svg+xml;

    # Static files — React dashboard
    location / {
        root ${client_dist};
        try_files \$uri \$uri/ /index.html;

        # Cache static assets aggressively
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
            expires 30d;
            add_header Cache-Control "public, immutable";
        }
    }

    # API proxy
    location /api/ {
        proxy_pass http://yetiforge_api;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    # Webhook endpoint
    location /webhook/ {
        proxy_pass http://yetiforge_api;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # Block access to sensitive files
    location ~ /\. {
        deny all;
        return 404;
    }
}
NGINXCONF

        $SUDO_CMD cp /tmp/yetiforge-nginx.conf /etc/nginx/sites-available/yetiforge
        $SUDO_CMD ln -sf /etc/nginx/sites-available/yetiforge /etc/nginx/sites-enabled/yetiforge

        # Remove default site if it exists and this is the only site
        if [[ -f /etc/nginx/sites-enabled/default ]]; then
            prompt_yn "Remove default Nginx site?" "y" REMOVE_DEFAULT
            if [[ "$REMOVE_DEFAULT" == "true" ]]; then
                $SUDO_CMD rm -f /etc/nginx/sites-enabled/default
                log_success "Default Nginx site removed"
            fi
        fi

        # Test nginx config
        if $SUDO_CMD nginx -t >> "$INSTALL_LOG" 2>&1; then
            $SUDO_CMD systemctl reload nginx
            log_success "Nginx configured for ${server_name}"
        else
            log_error "Nginx configuration test failed!"
            log_info "Check with: sudo nginx -t"
            $SUDO_CMD rm -f /etc/nginx/sites-enabled/yetiforge
            log_warn "Nginx config saved but not activated. Fix manually."
        fi
    else
        log_info "No domain configured — skipping Nginx setup"
        log_info "Dashboard accessible at http://YOUR_IP:${CFG_PORT:-3069}"
    fi

    # ──────────────────────────────────────────────
    # Firewall
    # ──────────────────────────────────────────────
    if [[ "$UFW_AVAILABLE" == "true" ]]; then
        log_step "Configuring firewall rules..."
        prompt_yn "Configure UFW firewall rules? (opens ports 80, 443, ${CFG_PORT:-3069})" "y" SETUP_UFW

        if [[ "$SETUP_UFW" == "true" ]]; then
            $SUDO_CMD ufw allow 80/tcp >> "$INSTALL_LOG" 2>&1
            $SUDO_CMD ufw allow 443/tcp >> "$INSTALL_LOG" 2>&1
            $SUDO_CMD ufw allow "${CFG_PORT:-3069}/tcp" >> "$INSTALL_LOG" 2>&1
            $SUDO_CMD ufw allow 22/tcp >> "$INSTALL_LOG" 2>&1  # Don't lock ourselves out

            if ! $SUDO_CMD ufw status | grep -q "Status: active"; then
                prompt_yn "Enable UFW firewall?" "y" ENABLE_UFW
                if [[ "$ENABLE_UFW" == "true" ]]; then
                    echo "y" | $SUDO_CMD ufw enable >> "$INSTALL_LOG" 2>&1
                    log_success "Firewall enabled"
                fi
            fi
            log_success "Firewall rules configured"
        fi
    else
        log_info "No UFW — ensure ports 80, 443, ${CFG_PORT:-3069} are open"
    fi

    echo ""
    log_success "Services configured"
}
